spring.application.name=ColleageManagement

spring.datasource.url=jdbc:mysql://localhost:3306/sreekanth?useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=P@ssw0rd@1914

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=6060



